server:
  name: "my-mcp-server"
  version: "1.0.0"
  transport: sse
  host: "127.0.0.1"
  port: 3000
  max_connections: 100
  timeout_ms: 30000

resources:
  root_path: "./resources"
  allowed_schemes:
    - file
  max_file_size: 10485760
  enable_templates: true

security:
  enable_auth: false
  rate_limit:
    requests_per_minute: 60
    burst_size: 10
  allowed_origins:
    - "*"

logging:
  level: "info"
  format: "pretty"